export const NEST_BROKER_OPTIONS = "NEST_BROKER_OPTIONS";
export const BROKER_TYPE_RABBIT = "BROKER_TYPE_RABBIT";
export const BROKER_TYPE_KAFKA = "BROKER_TYPE_KAFKA";
export const BROKER_SUBSCRIBE = "BROKER_SUBSCRIBE";
